MvcPL/Models/PostViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcPL.Models
{
    public class PostViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "You need fill the text of the article"), DataType(DataType.MultilineText)]
        public string Content { get; set; }
        public string Tag { get; set; }
        [Display(Name="Time of creation")]
        public DateTime CreateTime { get; set; }
        [Display(Name = "Time of last updating")]
        public DateTime UpdateTime { get; set; }

        public int BlogId { get; set; }
    }
}

MvcPL/Controllers/BlogController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BLL.Interfaces.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Models;

namespace MvcPL.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IUserService _userService;

        public BlogController(IBlogService blogService, IUserService userService)
        {
            _blogService = blogService;
            _userService = userService;
        }

        //public ActionResult CreatePost(int? id)
        //{
        //    if (id == null)
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        //    if(!HasAccess((int)id))
        //        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

        //    return RedirectToAction("Create", "Post", new {id});
        //}

        [AllowAnonymous]
        public ActionResult Index()
        {
            var blogs = _blogService.GetAllBlogEntities().Select(blog => blog.ToMvcBlog());
            return View(blogs);
        }

        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var blog = _blogService.GetBlogEntity((int)id);
            if (blog == null)
                return HttpNotFound();

            return View(blog.ToMvcBlog());
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (!HasAccess((int)id))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var blog = _blogService.GetBlogEntity((int) id);
            if (blog != null)
                return View("BlogExistsError");

            TempData["UserId"] = id;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(BlogViewModel blogViewModel)
        {
            if (!ModelState.IsValid)
                return View(); 
            blogViewModel.UserId = (int)TempData["UserId"];
            blogViewModel.CreateTime = DateTime.Now;
            _blogService.CreateBlog(blogViewModel.ToBllBlog());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (!HasAccess((int)id))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var blog = _blogService.GetBlogEntity((int)id);
            if (blog == null)
                return HttpNotFound();

            return View(blog.ToMvcBlog());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(BlogViewModel blogViewModel)
        {
            if (!ModelState.IsValid)
                return View(blogViewModel);
            _blogService.UpdateBlog(blogViewModel.ToBllBlog());
            return RedirectToAction("Index");
        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (!HasAccess((int)id))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var blog = _blogService.GetBlogEntity((int)id);
            if (blog == null)
                return HttpNotFound();

            return View(blog.ToMvcBlog());
        }


        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var product = _blogService.GetBlogEntity(id);
            _blogService.DeleteBlog(product);
            return RedirectToAction("Index");
        }

        #region ChildActions

        [ChildActionOnly, AllowAnonymous]
        public string GetNameById(int id)
        {
            return _blogService.GetBlogEntity(id).BlogName;
        }
        #endregion

        private bool HasAccess(int id)
        {
            return id == _userService.GetIdByLogin(User.Identity.Name) || User.IsInRole("Administrator");
        }
    }
}

MvcPL/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BLL.Interfaces.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Models;

namespace MvcPL.Controllers
{
    //USERS CAN CHANGE ANOTHER'S POST
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly IUserService _userService;
        private readonly ICommentService _commentService; //ajax запросы

        public PostController(IPostService postService, ICommentService commentService, IUserService userService)
        {
            _postService = postService;
            _userService = userService;
            _commentService = commentService;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = _postService.GetAllPostEntities().Select(p => p.ToMvcPost());
            return View(posts);
        }

        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var post = _postService.GetPostEntity((int)id);
            if (post == null)
                return HttpNotFound();

            var comments = _commentService.GetAllPostEntities().Where(c => c.PostId == id).
                OrderByDescending(c => c.CreateTime).Select(c => c.ToMvcComment());
            TempData["Comments"] = comments.ToList();

            return View(post.ToMvcPost());
        }

        [AllowAnonymous]
        public ActionResult Search(string searchText)
        {
            ViewBag.SearchText = searchText;
            var postsWithSameTag = _postService.GetAllPostEntities().
                Where(p => p.Tag.Equals(searchText, StringComparison.OrdinalIgnoreCase)).Select(p => p.ToMvcPost());
            var postWithSameContent = _postService.GetAllPostEntities().
                Where(p => p.Content.Contains(searchText)).Select(p => p.ToMvcPost());
            var posts = new List<PostViewModel>();
            posts.AddRange(postsWithSameTag);
            posts.AddRange(postWithSameContent);

            return View(posts);
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (!HasAccess((int)id))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            TempData["BlogId"] = id;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(PostViewModel postViewModel)
        {
            if(!ModelState.IsValid)
                return View();
            postViewModel.BlogId = (int)TempData["BlogId"];
            postViewModel.CreateTime = DateTime.Now;
            postViewModel.UpdateTime = DateTime.Now;
            _postService.CreatePost(postViewModel.ToBllPost());
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var post = _postService.GetPostEntity((int)id);
            if (post == null)
                return HttpNotFound();

            if(!HasAccess(post.BlogId))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(post.ToMvcPost());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(PostViewModel postViewModel)
        {
            postViewModel.UpdateTime = DateTime.Now;
            _postService.UpdatePost(postViewModel.ToBllPost());
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var post = _postService.GetPostEntity((int)id);
            if (post == null)
                return HttpNotFound();

            if (!HasAccess(post.BlogId))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(post.ToMvcPost());
        }


        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var product = _postService.GetPostEntity(id);
            _postService.DeletePost(product);
            return RedirectToAction("Index");
        }

        private bool HasAccess(int id)
        {
            return id == _userService.GetIdByLogin(User.Identity.Name) || User.IsInRole("Administrator");
        }
    }
}

MvcPL/Controllers/UserController.cs
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BLL.Interfaces.Services;
using MvcPL.Infrastructure.Mappers;
using MvcPL.Models;

namespace MvcPL.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _service;

        public UserController(IUserService service)
        {
            _service = service;
        }
        
        [AllowAnonymous]
        public ActionResult GetImage(int id)//!!!!!!!!
        {
            var image = _service.GetUserEntity(id)?.Image;
            if (image == null)
                return File(Server.MapPath("~/App_Data/NoAvatar.png"), "image/png");
            return File(image, "image/jpeg");
        }
        
        [AllowAnonymous]
        public ActionResult Index()
        {
            var users = _service.GetAllUserEntities().Select(user => user.ToMvcUser());
            return View(users);
        }

        
        [HttpGet, Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        //Only admin can use this function
        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Administrator")]
        public ActionResult Create(UserViewModel userViewModel, HttpPostedFileBase[] uploadImage)
        {
            if (!ModelState.IsValid)
                return View();
            if (uploadImage[0] != null)
            {
                byte[] imageData;
                using (var binaryReader = new BinaryReader(uploadImage[0].InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage[0].ContentLength);
                }

                userViewModel.Image = imageData;
            }

            userViewModel.Password = GetMD5Hash(userViewModel.Password);//we get response with the open password...?
            _service.CreateUser(userViewModel.ToBllUser());
            return RedirectToAction("Index");
        }
        

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = _service.GetUserEntity((int)id);

            if (user == null)
                return HttpNotFound();

            if (!HasAccess(user.Login))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(user.ToMvcUser());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(UserViewModel userViewModel, HttpPostedFileBase[] uploadImage)
        {
            if (!ModelState.IsValid)
                return View(userViewModel);
            if (uploadImage[0] != null)
            {
                byte[] imageData;
                using (var binaryReader = new BinaryReader(uploadImage[0].InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage[0].ContentLength);
                }

                userViewModel.Image = imageData;
            }
            
            _service.UpdateUser(userViewModel.ToBllUser());
            FormsAuthentication.SetAuthCookie(userViewModel.Login, false);//проверить без изменения логина
            return RedirectToAction("Details", new { id = userViewModel.Id});
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = _service.GetUserEntity((int)id);
            if (user == null)
                return HttpNotFound();

            if (!HasAccess(user.Login))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            return View(user.ToMvcUser());
        }


        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var user = _service.GetUserEntity(id);

            if(!HasAccess(user.Login))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            if (User.IsInRole("Administrator"))
            {
                _service.DeleteUser(user);
                return RedirectToAction("Index");
            }
            _service.DeleteUser(user);
            return RedirectToAction("Logoff", "Account");
        }

        [HttpGet, AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var product = _service.GetUserEntity((int)id);
            if (product == null)
                return HttpNotFound();

            return View(product.ToMvcUser());
        }

        #region ChildActions
        [ChildActionOnly, AllowAnonymous]
        public int? GetIdByLogin(string login)
        {
            return _service.GetIdByLogin(login);
        }

        [ChildActionOnly, AllowAnonymous]
        public string GetLoginById(int id)
        {
            return _service.GetLoginById(id);
        }
        #endregion

        private bool HasAccess(string login)
        {
            return login == User.Identity.Name || User.IsInRole("Administrator");
        }

        private string GetMD5Hash(string input)
        {
            var md5Hasher = MD5.Create();
            byte[] data = md5Hasher.ComputeHash(Encoding.Default.GetBytes(input));
            var sBuilder = new StringBuilder();
            foreach (var b in data)
                sBuilder.Append(b.ToString("x2"));
            return sBuilder.ToString();
        }
    }
}

MvcPL/Views/Post/Create.cshtml
@model MvcPL.Models.PostViewModel

@{
    ViewBag.Title = "Create post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Create post</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Tag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tag)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Content, new {rows="20", style="width: 100%"})
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Add post" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Cancel", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPL/Views/Post/Delete.cshtml
@model MvcPL.Models.PostViewModel

@{
    ViewBag.Title = "Delete post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this post?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete post" class="btn btn-default" />
            <br />
            @Html.ActionLink("Cancel", "Index")
        </div>
    }
</div>

MvcPL/Views/Post/Details.cshtml
@using MvcPL.Models
@model PostViewModel

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var comments = (IEnumerable<CommentViewModel>)TempData["Comments"];
    if (User.Identity.IsAuthenticated)
    {
        TempData["PostId"] = Model.Id;
        TempData["UserId"] = Html.Action("GetIdByLogin", "User", new{login=User.Identity.Name});
    }
}

<div>
    <h2>@Model.Title</h2>
    <p>@Model.Tag</p>
    @Html.ActionLink("Blog info", "Details", "Blog", new { id = Model.BlogId }, null)
    <hr/>
</div>

<div>
    @Html.DisplayFor(model => model.Content)
</div>
<br/>
<hr/>


@if (User.Identity.IsAuthenticated)
{
    <div>
        @using (Ajax.BeginForm("Create", "Comment", 
            new AjaxOptions{UpdateTargetId = "comments", InsertionMode = InsertionMode.InsertBefore}))
        {
            @Html.Hidden("PostId")
            @Html.Hidden("UserId")
            <div class="editor-field">
                <textarea name="Content" cols="100"></textarea>
            </div>
            <div>
                <input type="submit" value="Add comment"/>
            </div>
        }
    </div>
}
else
{
    @:You can leave a comment after @Html.ActionLink("registration", "Register", "Account") or 
    @Html.ActionLink("authorization", "Login", "Account")
}
<hr/>


<h4>Comments for this post:</h4>
<div id="comments">
    @foreach (var comment in comments)
    {
        <div class="row">
            <div class="col-md-1">
                <img width="50" height="50" src="@Url.Action("GetImage", "User", new { id = comment.UserId})" />
            </div>

            <div class="col-md-offset-1">
                <strong>@Html.Action("GetLoginById", "User", new { id = comment.UserId })</strong> 
                <=> @Html.DisplayFor(modelItem => comment.CreateTime)
                <br/>
                @Html.DisplayFor(modelItem => comment.Content)
            </div>
        </div>
        <hr/>
    }
</div>

<p>
    <br/>
    @if (User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Edit post", "Edit", new {id = Model.Id}) @:|
        @Html.ActionLink("Delete post", "Delete", new {id = Model.Id}) @:|
    }
    @Html.ActionLink("Back to list of posts", "Index")
</p>
@Scripts.Render("~/scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")

MvcPL/Views/Post/Edit.cshtml
@model MvcPL.Models.PostViewModel

@{
    ViewBag.Title = "Edit post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tag)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Content, new { @class = "form-control", rows = "15", cols = "100" })
            @Html.ValidationMessageFor(model => model.Content)
        </div>
        @Html.HiddenFor(model => model.CreateTime)

        <p>
            <input type="submit" value="Save changes" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Cancel", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPL/Views/Post/Index.cshtml
@model IEnumerable<MvcPL.Models.PostViewModel>

@{
    ViewBag.Title = "Posts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of existing posts</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateTime)
        </th>
        <th>
            Blog name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tag)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Title, "Details", "Post", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>
            <td>
                @Html.Action("GetNameById", "Blog", new { id = item.BlogId })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tag)
            </td>
        </tr>
    }

</table>

MvcPL/Views/Post/Search.cshtml
@model IEnumerable<MvcPL.Models.PostViewModel>

@{
    ViewBag.Title = ViewBag.SearchText;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search results: @ViewBag.SearchText</h2>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateTime)
            </th>
            <th>
                Blog name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tag)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Title, "Details", "Post", new { id = item.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateTime)
                </td>
                <td>
                    @Html.Action("GetNameById", "Blog", new { id = item.BlogId })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tag)
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>
        The search has not given any results
    </p>
}